### ISSUE TITLE
Staff Movement - Redeployment (Workflow)

### ISSUE THREAD

**Issue by Mandiklopper** [Mandiklopper/UBA-HR-Queries-Issues#1]
Email from Robert:

Please check why email notifications for staff movement is not going. A redeployment request for A07987 that has status s Requested, Awaiting management approval did not send a notification to Patricia.

I have checked the workflow monitor and there is no entry there.

Please treat as very urgent

**Comment by Mandiklopper** [comment]
http://senseable.co.za/scp/tickets.php?a=search&search-type=typeahead&query=236&number=236

**Comment by roberteta** [comment]
I cannot find this entry in staff movement

**Comment by Mandiklopper** [comment]
I have checked and I noticed that the new contract for redeployment did create.  See attached.
![a07987 redeployment](https://user-images.githubusercontent.com/33479066/32808177-da401e6a-c99a-11e7-80d2-e140c341a257.PNG)
