### ISSUE TITLE
Workflow - Personal Hospital Update

### ISSUE THREAD

**Issue by Mandiklopper** [Mandiklopper/UBA-HR-Queries-Issues#10]
Raised by Jacquelyn:

I initiated a hospital update on my profile for myself but the email content sent to me and my supervisor indicates the Hospital Change is for Dependent 1 (Child).

**Comment by Mandiklopper** [comment]
http://senseable.co.za/scp/tickets.php?id=117 - Assigned to JW

**Comment by Mandiklopper** [comment]
**Message has been amended and will now display the correct information**.  Please retest.

**Comment by roberteta** [comment]
Closed based on notification sent to a staff who made the same changes
