### ISSUE TITLE
MISSING DEPENDANTS TAB ON ESS - EMERGENCY!!!!

### ISSUE THREAD

**Issue by roberteta** [Mandiklopper/UBA-HR-Queries-Issues#102]
One of the Executive Directors is trying to access his deppendants via ESS in order to make changes to hospitals

He is not able to see the deendant tab abd on checking from my end, this tab has disappeared and there is a blank tab with no title and does not open when clicked. See screenshot attached

Please urgently look into this.

**Comment by Mandiklopper** [comment]
Solved by JW.
