### ISSUE TITLE
ACCESS/Approval of Staff Movement - Promotion

### ISSUE THREAD

**Issue by roberteta** [Mandiklopper/UBA-HR-Queries-Issues#103]
@ Chidi,

Please grant access to Ugochi Okafor  (A22454 ) to enable her approve Promotion Staff Movement on the single processing and multi-processing screens.

Her current role is UBA Corporate HR Specialist - Talent Management

**Comment by chidiif** [comment]
@roberteta, the role - **Corp HR Spec Talent Manager** has been modified to be able to modify staff movement requests.
