### ISSUE TITLE
ACCESS/Unable to Access PeopleConnect - Temitope Aileru

### ISSUE THREAD

**Issue by roberteta** [Mandiklopper/UBA-HR-Queries-Issues#106]
Staff, Temitope  Aileru is unable to access PeopleConnect using her UBA username and password.

Please check to confirm that he belongs to a group and has Preprod EndPoint login.

**Comment by chidiif** [comment]
Her setup-user login was bearing her maiden name – Ogunsanya. It has been resolved now.

Kindly advise user to login again.

**Comment by roberteta** [comment]
Successful login confirmed
