### ISSUE TITLE
Access - Wrong Profile assigned

### ISSUE THREAD

**Issue by roberteta** [Mandiklopper/UBA-HR-Queries-Issues#11]
Musa Abdullahi –CE01344(Teller with email address musa.abdullahi@ubagroup.com) was added to the HR Business Partner user group while Musa Abdul – A14139 (HRBP with email address musa.abdul@ubagroup.com) is in the ESS Group that is for all other staff.

Please make the following correction to their profiles;

•	Assign Musa Abdul – A14139 (HRBP) to HRBP profile
•	Assign Musa Abdullahi –CE01344(Teller) to ESS profile

**Comment by chidiif** [comment]
I believe it is same with case #16. Please confirm.

**Comment by Mandiklopper** [comment]
Closed - The same as #16
