### ISSUE TITLE
Access Control - Profile error

### ISSUE THREAD

**Issue by Mandiklopper** [Mandiklopper/UBA-HR-Queries-Issues#16]
Email send by Robert:

Musa Abdullahi –CE01344(Teller with email address musa.abdullahi@ubagroup.com) was added to the HR Business Partner user group while Musa Abdul – A14139 (HRBP with email address musa.abdul@ubagroup.com) is in the ESS Group that is for all other staff.

Please make the following correction to their profiles;

•	Assign Musa Abdul – A14139 (HRBP) to HRBP profile
•	Assign Musa Abdullahi –CE01344(Teller) to ESS profile

**Comment by chidiif** [comment]
Done

**Comment by Mandiklopper** [comment]
Completed.  UBA to retest.
