### ISSUE TITLE
ACCESS/Confirmation Team Access

### ISSUE THREAD

**Issue by Mandiklopper** [Mandiklopper/UBA-HR-Queries-Issues#22]
Please look into the access for the Confirmation Team.  On the Career tab they should be able to view and edit on the Confirmation and Guarantor Tab.  The other tabs on career should only be there for viewing purposes.  

Also give access to the contract tab on the employment contract.  Only viewing not creating, editing or deleting.

**Comment by chidiif** [comment]
Both Requests have been treated.
