### ISSUE TITLE
Implemented Staff Movement with no Email Notification

### ISSUE THREAD

**Issue by roberteta** [Mandiklopper/UBA-HR-Queries-Issues#27]
1. Redeployment for Charity Ojeh (A21659)

, was done and implemented with no email notification
2. Relief Assignment was processed for Francis Ikwue (A15483)  but there has been no notification received.

**Comment by Mandiklopper** [comment]
http://senseable.co.za/scp/tickets.php?id=120 - not yet assigned.

**Comment by Mandiklopper** [comment]
The left list issue has been resolved.  Please retest.

**Comment by roberteta** [comment]
Hello JW,

Please check why the Reassignment notification for Peter Nwachukwu (A09088) that was approved by GHHR earlier today and has status of implemented has not been sent out.
