### ISSUE TITLE
Staff Logon Access on PeopleConnect

### ISSUE THREAD

**Issue by jayekwueme** [Mandiklopper/UBA-HR-Queries-Issues#29]
Staff profiled in the UBA-Team Member HCM Operations user group cannot log into PeopleConnect successfully. 

They get a blank screen when they type their username and password.

**Comment by Mandiklopper** [comment]
Leave a comment

**Comment by chidiif** [comment]
Kindly provide staff Employee ID or Work Email Address

**Comment by chidiif** [comment]
@jayekwueme Kindly provide staff Employee ID or Work Email Address

**Comment by jayekwueme** [comment]
A16960 - afolabi.alade@ubagroup.com

**Comment by chidiif** [comment]
@jayekwueme Kindly ask the employee to login again.
