### ISSUE TITLE
Workflow - Staff Movement (Notification linked to reasons)

### ISSUE THREAD

**Issue by Mandiklopper** [Mandiklopper/UBA-HR-Queries-Issues#3]
Email received by Robert Eta:

Please note that the 3 items highlighted in yellow are redeployment reasons that are applicable to pre-approved redeployment. Such pre-approved redeployment request will be created and approved by the HRBPs (Team member & Team Lead) and not via the approval process that goes to the GHHR/GMD as the case may be.

**Comment by Mandiklopper** [comment]
http://senseable.co.za/scp/tickets.php?id=110 - Assigned to Jan Willem

**Comment by Mandiklopper** [comment]
This has now been implemented on the system - Completed by JW.

**Comment by roberteta** [comment]
A redeployment was done using one of these sub reason and it was implemented after approval by HRBP Team Lead. However no email notification went out.
