### ISSUE TITLE
Error Message In Creating  from ESS

### ISSUE THREAD

**Issue by Adebukola** [Mandiklopper/UBA-HR-Queries-Issues#30]
When trying to log exit request from ESS, the following  error keeps coming up under Exit reason & Sub reason when users try to save the exit request. 

359~MXR05 : Inactive record
6005~SXR06 : Inactive record

**Comment by Mandiklopper** [comment]
http://senseable.co.za/scp/tickets.php?id=137 - Not yet assigned on Senseable.

**Comment by Mandiklopper** [comment]
@Adebukola please retest.  This has been closed.

**Comment by roberteta** [comment]
A number of Exit Requests have been succesfully logged subsequently
