### ISSUE TITLE
Skills and Careers - Careers Screen

### ISSUE THREAD

**Issue by roberteta** [Mandiklopper/UBA-HR-Queries-Issues#31]
![img_20171109_164846_resized_20171109_045005126](https://user-images.githubusercontent.com/33485868/32617096-619e78fa-c574-11e7-9428-77af7eaa6316.jpg)

The careers screen has 4 instances where surname has been used wrongly as title for columns.

See attached screen shot

**Comment by Mandiklopper** [comment]
Mandi investigating.

**Comment by Mandiklopper** [comment]
http://senseable.co.za/scp/tickets.php?id=148 - Not yet assigned on Senseable

**Comment by Mandiklopper** [comment]
Delivery date: Monday Nov 27, 2017
Done on DEV2 requested to be patched on PREPOD.

**Comment by Mandiklopper** [comment]
Closed by Adebayo.  Please test.
