### ISSUE TITLE
STAFF MOVEMENT ERROR - INCORRECT REASON

### ISSUE THREAD

**Issue by roberteta** [Mandiklopper/UBA-HR-Queries-Issues#33]
A relief assignment processed for A21722 with effective date of 9/11 and end date of 29/11 had an error on processing with error message as 'incorrect reason'
--

**Comment by Mandiklopper** [comment]
Completed.

**Comment by Mandiklopper** [comment]
http://senseable.co.za/scp/tickets.php?id=130 - Closed by JW

**Comment by Mandiklopper** [comment]
Change to Staff Movements in content of message as discussed with Robert.

**Comment by roberteta** [comment]
The closure comment does not relate to this issue

**Comment by roberteta** [comment]
There is no way of retesting this particular case. Closure is based on the fact that no new cases have come up with this error.
