### ISSUE TITLE
Error on Relief Assignment Processed

### ISSUE THREAD

**Issue by roberteta** [Mandiklopper/UBA-HR-Queries-Issues#34]
A relief assignment processed for A22118 with effective date of 8/11 and end date of 17/11 had an error on processing with error message as 'Error creating new contract Selected notch is invalid for the selected grade'
A review of the Employment contract screen reveal the following;
1. The take-on data contract for this employee has no Grade (this is a mandatory field), but has a base notch
2. The new contract that the system tried to create with the relief assignment processed had no grade but had a base notch, nd also no end date
3. The contract for the resumption from relief assignment was not created.

**Comment by Mandiklopper** [comment]
@chidiif please give A15774 and A05164 access to SITE BR086

**Comment by chidiif** [comment]
Both A15774 and A05164 have access to all sites.

**Comment by Mandiklopper** [comment]
Closed.  Moved to implemented.
