### ISSUE TITLE
Setup of Employee Number Sequence

### ISSUE THREAD

**Issue by roberteta** [Mandiklopper/UBA-HR-Queries-Issues#38]
In response to the extract from the email from Mandi below, based on feedback below from HRIS Administrator, the last employee code issued on HRIS is A24216, so the sequence should start from **A24217**

After our discussion on Thursday afternoon I just want to confirm the process going forward on email.

We will change the Sequense numbers of the employee codes from NGxxxxxx to Axxxxxxx for now.  So when new employees start in the business the employee code that will be assigned will be with the Axxxxxxx.  Please advise which employee code the sequence should start with when the new staff members join the business?  We require this information to setup the sequence.  As Martin mentioned he will also create a field where the old employee code can be stored.  Going forward all employees even if contractors will follow this sequense as the Category will identify if the employee is a core employee or contractor.

Then when the system migrates to V12 we will use the down time to also convert employee codes by replacing Ax with NG and also updating the sequence setup.

**Comment by Mandiklopper** [comment]
http://senseable.co.za/scp/tickets.php?id=131 - Assigned to Martin

**Comment by roberteta** [comment]
Due to the promotion of seven (7) Graduate Trainee to Executive Trainee, the last issued employee ID on HRIS is now **A24223.**

**Comment by roberteta** [comment]
Hello Martin,
Please this request is critical as there are new hores to be onboarded this morning.

**Comment by Mandiklopper** [comment]
This has been completed and tested with onboarded staff.
