### ISSUE TITLE
Access to Extract Reports from Sage for import to HRIS

### ISSUE THREAD

**Issue by roberteta** [Mandiklopper/UBA-HR-Queries-Issues#39]
Please grants Oyebola Owoseni (A23512) access to extract reports for import to HRIS

See attached
[HRIS Export Templates.pdf](https://github.com/Mandiklopper/UBA-HR-Queries-Issues/files/1461493/HRIS.Export.Templates.pdf)

**Comment by Mandiklopper** [comment]
Chidi please look into this asap.

**Comment by chidiif** [comment]
@Mandiklopper, I suppose Oyebola fills the same role as Jacky? Please confirm if he should be elevated to Customer Admin.

**Comment by chidiif** [comment]
@roberteta Kindly confirm if Oyebola should have the same level of Access Jacky has - Customer Administrator.

**Comment by chidiif** [comment]
Done. Oyebola now have access to the Administration module.
