### ISSUE TITLE
 Approval of Transactions loaded by HRBP Team member

### ISSUE THREAD

**Issue by roberteta** [Mandiklopper/UBA-HR-Queries-Issues#41]
A HRBP Team member (A23401) initiated a relief assignment for a staff (A17147) on People Connect but in the course of approval by the HRBP Team Lead (A23401's supervisor), the staff’s supervisors name (Ejiroghene Kara) appears as the approver in place of A23401's supervisor details. However this relief assignment is available for approval by the HRBP Team lead

However staff movement initiated for A23413 on People Connect by A23401 had  HRBP Team Lead (A23401's supervisor), as the approver and the request was approved.

**Comment by Mandiklopper** [comment]
Assigned to Mandi to first test.

**Comment by Mandiklopper** [comment]
Initiator is now copied in.    Completed by JW.  Please test.

**Comment by Mandiklopper** [comment]
Also included the stakeholders and created a payroll stakeholder group with this mail  Payrollvalidation@ubagroup.com.  According to me this is closed.  Please let me know.

**Comment by roberteta** [comment]
The issue was not the fact that initiator was not copied in notifications or the inclusion of stakeholders in the notifications. The issue was different outcomes for staff movement loaded by HRBP team member for staff in sites mapped to him. For some staff it picks the staff's supervisor as approver, for other staff'it picks the HRBP Team lead as approver. These are all staff movement loaded by the HRBP team member.

**Comment by Mandiklopper** [comment]
![staff movement a17147](https://user-images.githubusercontent.com/33479066/33018122-c909bb26-cdfd-11e7-9448-37123d420967.PNG)

**Comment by Mandiklopper** [comment]
Closed by JW.  Please retest.

**Comment by roberteta** [comment]
No recent reoccurence
