### ISSUE TITLE
Correct Grades for Executive band

### ISSUE THREAD

**Issue by Mandiklopper** [Mandiklopper/UBA-HR-Queries-Issues#44]
Message from Robert:

Hello Mandi,  Attached is the updated sheet showing the correct sequence for grades in the Executive Management band.
See extract of section where the sequence was wrong and now corrected (GGM > ED > DMD > GMD)

Emailed @Yinka123 with the detail to complete on all environments and provide feedback once done.

**Comment by Yinka123** [comment]
Issue has been fixed.
