### ISSUE TITLE
Notification to HRIS to expand grade range of positions not going through

### ISSUE THREAD

**Issue by Adebukola** [Mandiklopper/UBA-HR-Queries-Issues#45]
When redeployment is initiated for an employee to be redeployed into a position that has a grade range outside of the employee's own grade, a message to notify HRIS pops up.  Currently, the system is not sending notification to HRIS so that HRIS can expand the grade range.

**Comment by Mandiklopper** [comment]
http://senseable.co.za/scp/tickets.php?id=135 - Not yet assigned on Senseable

**Comment by Mandiklopper** [comment]
HRIS position was missing from the recipient tab of the workflow. Corrected now, please retest.
