### ISSUE TITLE
EXIT REQUEST - BLANK NOTIFICATION

### ISSUE THREAD

**Issue by roberteta** [Mandiklopper/UBA-HR-Queries-Issues#48]
The Exit Request email notification for employee A11552  is blank.

The following fields are blank in the notification;

Staff Grade:
Job Title:
Staff Location:
Effective Date:

**Comment by Mandiklopper** [comment]
http://senseable.co.za/scp/tickets.php?id=141 - Not assigned yet on Senseable.

**Comment by Mandiklopper** [comment]
Resolved, please retest.
