### ISSUE TITLE
Incorrect Job Grade for A06919 - J0013013200707

### ISSUE THREAD

**Issue by jayekwueme** [Mandiklopper/UBA-HR-Queries-Issues#50]
Employee A06919 - J0013013200707 has an incorrect grade attached to his profile.

Can we re-validate the grades for every employee again?

![a06919](https://user-images.githubusercontent.com/29643618/32772955-df79e6f4-c927-11e7-8f31-34c276db9d39.jpg)

**Comment by Mandiklopper** [comment]
@jayekwueme  what should the grade be for this employee?

**Comment by jayekwueme** [comment]
@Mandiklopper  BO - Banking Officer

**Comment by Mandiklopper** [comment]
@carldek to update with import

**Comment by carldek** [comment]
Update done
