### ISSUE TITLE
HMO DOWNLOAD ON PEOPLE'S CONNECT

### ISSUE THREAD

**Issue by roberteta** [Mandiklopper/UBA-HR-Queries-Issues#51]
Kindly provide a download of medical list from PeopleConnect. This download is sent to the HMO (Avon) on the 15th of every month and THIS IS DUE TOMORROW.

Download required- 

•	Consolidated List
•	Hospital changes
•	Exits
•	Additions

Sample report attached
[HMO Download Template.xlsx](https://github.com/Mandiklopper/UBA-HR-Queries-Issues/files/1470282/HMO.Download.Template.xlsx)

**Comment by Mandiklopper** [comment]
Assigned to Yinka and guided by Mandi.

**Comment by Yinka123** [comment]
I have created the report templates, kindly review and let me know. Also i need more information on what you want to see on the last requirement.

**Comment by Mandiklopper** [comment]
Completed the report with information extracted from system.  Final report will only be done with Reports going live.

**Comment by roberteta** [comment]
Report output was unreliable due to imported data. Report was manually generated via transactions een on WF monitor
