### ISSUE TITLE
Update on Position Code - A12973_J016003280033

### ISSUE THREAD

**Issue by bldre03** [Mandiklopper/UBA-HR-Queries-Issues#52]
Correct position code for A12973 should be J016003280033.
![screenshot_a12973](https://user-images.githubusercontent.com/33657390/32788134-b24118c0-c958-11e7-9c58-2399e391a37c.png)

**Comment by Mandiklopper** [comment]
@bldre03 please advise if this was the position for this employee from the start of employment at UBA or when did he start in this position originally?

**Comment by Mandiklopper** [comment]
Completed by Data take on by Carl.

**Comment by roberteta** [comment]
This has not been done.
Correct position code for A12973 should be J016003280033.
Current position for A12973 is J0160032800000

**Comment by Mandiklopper** [comment]
@carldek to complete with import.

**Comment by carldek** [comment]
Update done

**Comment by bldre03** [comment]
Dear Team,

This has not been resolved.


Regards,

**Comment by Mandiklopper** [comment]
@bldre03 this was corrected by @carldek.  Then @jayekwueme provided positions yesterday on a position template (with purple heading) and that was updated accordingly.  Please now indicate what the correct position is.  @roberteta this is very confusing for us getting different data from 2 different sources.

**Comment by bldre03** [comment]
Good morning Mandi,

The staff was on relief assignment when data was migrated to PeopleConnect.

Kindly adopt the position code Jacquleyn advised.


Best Regards,

**Comment by Mandiklopper** [comment]
@carldek we can leave the position then as is.  I am closing this ticket.
