### ISSUE TITLE
Update on Position code for A16903

### ISSUE THREAD

**Issue by bldre03** [Mandiklopper/UBA-HR-Queries-Issues#56]
Dear Mandy,

Kindly assist to update employee details below.

Empl ID - A16903
Standard Job - Head of Processing
Position Code - J014600030035.
![a16903_effiong helen](https://user-images.githubusercontent.com/33657390/32791510-7f448d36-c961-11e7-88a1-4e394de5d680.png)

Regards,

**Comment by Mandiklopper** [comment]
Completed with take on done by Carl.

**Comment by roberteta** [comment]
This has not been done.  Current details on the system is as follows;

Empl ID - A16903
Standard Job - Head of Processing
Position Code - J0146000300000

**Comment by Mandiklopper** [comment]
@carldek to complete with an import

**Comment by carldek** [comment]
Update done
