### ISSUE TITLE
Exit Notification Without Employee Name

### ISSUE THREAD

**Issue by Adebukola** [Mandiklopper/UBA-HR-Queries-Issues#58]
Exit notification does not have employee name.  The notification is produced below.  's' to be added to item below 

Dear Atinuke Oladele,

A final exit has been logged for the employee, with details below:

Employee ID: A21084
Contract number: A21084NG0001

The exit clearance checklist has been generated, please attend to ALL relevant item

Thank you

**Comment by Mandiklopper** [comment]
Linked this detail to ticket 21 and closing this ticket.

**Comment by roberteta** [comment]
This is not the same as ticket 21. This is a request for the inclusion of the name of the employee in the exit notification.
Dear Atinuke Oladele,

A final exit has been logged for the employee, with details below:

Employee ID: A21084
Employee Name: John Doe
Contract number: A21084NG0001
Position:
Dept/Branch:
Location

The exit clearance checklist has been generated, please attend to ALL relevant item

Thank you

**Comment by Adebukola** [comment]
This has not yet been closed.  Below is the email notification received today without name of employee.  Please close out including the additional fields that Robert mentioned above.

From: PeopleConnect@ubagroup.com [mailto:PeopleConnect@ubagroup.com] 
Sent: Friday, November 17, 2017 12:31 PM
To: Oladele, Atinuke
Subject: Final exit: CE01814NG0001

Dear Atinuke Oladele,

A final exit has been logged for the employee, with details below:

Employee ID: CE01814
Contract number: CE01814NG0001

The exit clearance checklist has been generated, please attend to ALL relevant item

Thank you

**Comment by Mandiklopper** [comment]
Ticket 292 - Assigned to Pierre on Senseable

**Comment by Mandiklopper** [comment]
Closed by Pierre.  Please retest.

**Comment by Mandiklopper** [comment]
Pierre has advised that this has now been fixed.  Please retest.

**Comment by roberteta** [comment]
Can only test following a recent load of final exit. Feedback will be provided

**Comment by roberteta** [comment]
The request was for the inclusion of more than employee name as per comment entered 5days ago.

The notification should be as shown below

Dear Atinuke Oladele,

A final exit has been logged for the employee, with details below:

Employee ID: A21084
Employee Name: John Doe
Contract number: A21084NG0001
Position: ????
Dept/Branch: ????
Location: ?????

The exit clearance checklist has been generated, please attend to ALL relevant item

Thank you

**Comment by Mandiklopper** [comment]
Reopened on Senseable.

**Comment by Mandiklopper** [comment]
Closed by Pierre
