### ISSUE TITLE
Staff movement - Workflow and X3 Awaiting processing function

### ISSUE THREAD

**Issue by Mandiklopper** [Mandiklopper/UBA-HR-Queries-Issues#6]
See issues brought to my attention by HRBP team Lead;

No email notification was received by HRBP Team Lead (Kayode Jamgbadi) for See issues brought to my attention by HRBP team Lead; 

1. No email notification was received by HRBP Team Lead (Kayode Jamgbadi) for request for relief assignment logged by HRBP Team member for a number of staff. sample are A16814, A21596, A23413 

2. The HRBP Team Lead has no records under the Actions Awaiting my attention category, but these records are visible in the category 'Awaiting HR action'

**Comment by Mandiklopper** [comment]
Assigned to JW

**Comment by Mandiklopper** [comment]
Addressed by JW and communicated to Robert to give feedback.

**Comment by roberteta** [comment]
The Actions Awaiting my Action does not limit the staff movements to only those of the HRPB in question.

**Comment by Mandiklopper** [comment]
Closed by JW.  Please retest.
