### ISSUE TITLE
Selected notch is invalid error

### ISSUE THREAD

**Issue by Mandiklopper** [Mandiklopper/UBA-HR-Queries-Issues#7]
Email from Robert Eta:

Attempts to process Staff Movement in the error/Awaiting processing category came up with the error message 'Selected notch is invalid for the selected grade' for A09594 (Already have a ticket open for this)

**Comment by Mandiklopper** [comment]
http://senseable.co.za/scp/tickets.php?id=54# - Assigned to Pierre van Zyl

**Comment by Mandiklopper** [comment]
Completed by Pierre on senseable.

**Comment by roberteta** [comment]
No recent record with this error message.
