### ISSUE TITLE
EMPLOYEE NAMES NOT ON EXIT REQUEST SCREEN

### ISSUE THREAD

**Issue by roberteta** [Mandiklopper/UBA-HR-Queries-Issues#77]
The right panel on the Exit Request Screen (Exit Management > Exit Request) does not have the names of the employees.
![exit request screen](https://user-images.githubusercontent.com/33485868/33015878-a3cf7622-cdec-11e7-879a-95f1d2228606.jpg)

The employee name should be inserted after the employee ID column.

**Comment by roberteta** [comment]
Navigation : Personnel Administration > Exit Management > Exit Request

**Comment by Mandiklopper** [comment]
http://senseable.co.za/scp/tickets.php?id=167 - Not yet assigned on senseable

**Comment by Mandiklopper** [comment]
Delivery date: Monday Nov 27, 2017
Done on DEV2 requested to be patched on PREPOD.

**Comment by roberteta** [comment]
Please confirm when this patching to PREPROD will be done and this is impacting efficiency on the Exit Management team

**Comment by Mandiklopper** [comment]
Closed.  Please test.
