### ISSUE TITLE
Exit Questionnaire question width

### ISSUE THREAD

**Issue by Mandiklopper** [Mandiklopper/UBA-HR-Queries-Issues#78]
The question field of the Exit Questionnaire on self service is so wide, the employees don't realise they have to scroll to the right to respond to the question.

A couple of support calls are logged due to this.

Please try to make it narrower (less than screen width) and rather wrap the question.

**Comment by Mandiklopper** [comment]
http://senseable.co.za/scp/tickets.php?id=156 - Assigned to Adebayo Shoyoola

**Comment by Mandiklopper** [comment]
Completed by Adebayo Shoyoola .  Please retest

**Comment by roberteta** [comment]
Looks OK
