### ISSUE TITLE
HRBP not getting notification of exit request but supervisor getting notification

### ISSUE THREAD

**Issue by Adebukola** [Mandiklopper/UBA-HR-Queries-Issues#84]
As per BRD, only HRBPs need to be notified when employee logs exit request.  Supervisors are not to get the request until HRBP works on it.  Right now, supervisors get the request once employees log the request while HRBPs do not get notification.

**Comment by Mandiklopper** [comment]
http://senseable.co.za/scp/tickets.php?id=194 - not assigned on Senseable yet

**Comment by Mandiklopper** [comment]
This has been solved.

**Comment by roberteta** [comment]
Only HRBPs mapped to the site was notified
