### ISSUE TITLE
ACCESS/HRBP Team Member to have modify access on Exit Interview Screen

### ISSUE THREAD

**Issue by Adebukola** [Mandiklopper/UBA-HR-Queries-Issues#85]
HRBP Team Members as well as Team Leads should have access to modify the exit request.  Please note that this means the three fields in the Exit Interview tab should be editable by them.  Exit details entered by staff should not be editable by HRBPs

**Comment by Mandiklopper** [comment]
@chidiif please assist

**Comment by chidiif** [comment]
This has been done.

**Comment by chidiif** [comment]
@Adebukola, Kindly confirm the users in both roles are happy to enable me close the case.
