### ISSUE TITLE
RREDEPLOYMENT NOTIFICATION SENT OUT FOR RELIEF ASSIGNMENTS LOADED.URGENT!!!!!!!!!

### ISSUE THREAD

**Issue by roberteta** [Mandiklopper/UBA-HR-Queries-Issues#88]
Hello JW,

Please URGENTLY look into why Redeployment notifications are being sent out for Relief Assignments loaded on the system. Loading on GitHub as well.
Please see a sample redeployment notification below for a relief assignment that was loaded on the system.
Please look into this urgently as it has serious implications since it gives the staff and supervisors the wrong impression.

**Comment by roberteta** [comment]
@ JW, Please see clarification by a HRBP Team lead

Dear Robert,

Notifications received when Relief Assignments are initiated by HRBP Team Members are  ‘Redeployment’ notifications.

However, the system shows Relief Assignment and a Relief Assignment notification is sent to staff upon approval of the transaction.

Thank you

**Comment by Mandiklopper** [comment]
Closed by JW
