### ISSUE TITLE
Approved Relief Assignments not impacting 

### ISSUE THREAD

**Issue by roberteta** [Mandiklopper/UBA-HR-Queries-Issues#89]
Hello JW,

Please see complaint by a HRBP team Lead - Ifeyinwa Unobagha

When I accept and save relief assignments, they are not impacted. They still remain on my “Awaiting my action” list.
 
Examples are below
•	A00940 – GRACE AMEH
•	A02557 – ADAEZE IYKE-MODOZIE
•	A07677 – NOEL NWAWOLO
•	A09521 – RITA OTUGHWOR

Regards

**Comment by Mandiklopper** [comment]
https://senseable.co.za/scp/tickets.php?id=202 - Not yet assigned on Senseable.

**Comment by Mandiklopper** [comment]
This has been solved. @roberteta please ask Ifeyinwa Unobagha to approve the transactions again.

**Comment by roberteta** [comment]
@JW,
See feedback below from  Ifeyinwa Unobagha

•	A00940 – GRACE AMEH
•	A02557 – ADAEZE IYKE-MODOZIE
•	A07677 – NOEL NWAWOLO
•	A09521 – RITA OTUGHWOR

Out of the 4 requests above, I was able to treat for 2 out of the initial 4 ( Adaeze Iyke-Modozie and Grace Ameh); and also 2 fresh initiations (Omon Okogie and Ese Oruese)

The pending two (A07677 & A09521) now have dates in the past  (Nov 26th); so have now expired….. 

How do we regularize these records on PeopleConnect 
•	Noel Nwawolo – A07677
•	Rita Otughwor – A09521

However, the same compliant still applies to:

1.	TEMILADE AKINJINRIN – A12901
2.	OSAGIE IKPE – A16992
3.	AGNES ERUZEGBUA – A13463
4.	ENOBONG UDOH – A21025
5.	OBIANUGO OKPARA – A22441

**Comment by jw** [comment]
Sorry,

I am the wrong recipient, I fear...

Regards,
Jan Willems

**Comment by Mandiklopper** [comment]
Closed by JW.
