### ISSUE TITLE
PROCESSES RELIEF ASSIGNMENTS NOT IMPACTING THUS NO NOTIFICATIONS ARE SENT OUT

### ISSUE THREAD

**Issue by roberteta** [Mandiklopper/UBA-HR-Queries-Issues#91]
@ JW,

Please look into the complaint below urgently

Dear Robert,
 
Please help check my profile.
 
When I accept and save relief assignments, they are not impacted. They still remain on my “Awaiting my action” list.
 
I have the following relief assignments pending since Friday
•	A00940 – GRACE AMEH
•	A02557 – ADAEZE IYKE-MODOZIE
•	A07677 – NOEL NWAWOLO
•	A09521 – RITA OTUGHWOR
 
Please assist urgently as it is impacting business
 
Thank you

Ifeyinwa Unobagha   (A05164)
HRBP, Abuja, South and East
--

**Comment by Mandiklopper** [comment]
Already logged on ticket 89 and assigned on Senseable.  Will give feedback soon.
