### ISSUE TITLE
Employee A24252 Oyebamiji Moradeke cannot be progressed from arrival screen

### ISSUE THREAD

**Issue by Adebukola** [Mandiklopper/UBA-HR-Queries-Issues#93]
The record for employee A24252 on the arrival screen cannot be saved by HRBP Team Lead so that it can move on. The save button is greyed out and not highlighted every time the Team Lead tries to save it.

**Comment by Mandiklopper** [comment]
@Adebukola I see that the information has been saved on the arrival screen for this employee.  The Offer accepted option has been greyed out.  Once this option has been selected no changes can be made on the record.  Did they click on offer accepted?

**Comment by Mandiklopper** [comment]
I am looking into this.  Will give you feedback soon.

**Comment by Mandiklopper** [comment]
This has now been solved.  The employee does have a contract and employee record.
