### ISSUE TITLE
AWAITING END DATES STAFF MOVEMENT

### ISSUE THREAD

**Issue by roberteta** [Mandiklopper/UBA-HR-Queries-Issues#95]
Please investigate the following staff movements and advice on next steps to address these

1.  A07677 /Status (Awaiting End Date) / Message (Record doesn't exist)

2.  A09788 / Status (Awaiting End Date) / Message (Invalid dates)

HRBP Team Leads captured ne end dates using the Extension column pior to attempts to approve the request.

Note that other request loaded  with end dates in the pasts have been successfully approved.

Regards

**Comment by Mandiklopper** [comment]
@roberteta According to me A07677 was treated by ticket #89.  Please confirm.
A09788 has 3 contracts on the system and it shows the correct dates for all the contracts.  Please let me know if this item is also still an issue?  Currently I do see that the Staff movement screen shows awaiting end date but everything was approved and transaction completed.

**Comment by roberteta** [comment]
Confirmed both have been treated evn though the error record for A09788 is still on the Staff movement screen
