### ISSUE TITLE
Migrate Employee Account Numbers data to newly created field on PeopleConnect

### ISSUE THREAD

**Issue by jayekwueme** [Mandiklopper/UBA-HR-Queries-Issues#97]
A reminder to migrate employee account numbers data provided at take-on to the newly created field (UBA Account Number) on PeopleConnect

**Comment by Mandiklopper** [comment]
@carldek please attend to this.

**Comment by carldek** [comment]
Hi Jacquelyn, Martin migrated the bank account numbers yesterday afternoon. Please check and confirm.
I also made a few checks this morning and all looks ok

**Comment by jayekwueme** [comment]
Confirmed ok
